stages:
  - test

run-tests:
  stage: test
  image: php:8.3 # Use a recent PHP image
  before_script:
    # Install Composer dependencies
    - curl -sS getcomposer.org | php
    - php composer.phar install
  script:
    # Run the PHPUnit tests
    - vendor/bin/phpunit tests/CalculatorTest.php

